# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disk',
            options={'verbose_name': '磁盘', 'verbose_name_plural': '磁盘'},
        ),
        migrations.AlterModelOptions(
            name='ram',
            options={'verbose_name': '内存', 'verbose_name_plural': '内存'},
        ),
        migrations.RenameField(
            model_name='disk',
            old_name='disk_iface',
            new_name='iface_type',
        ),
    ]
