# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 03:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20161114_1136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='mf',
            new_name='manufactory',
        ),
    ]
